markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: 生活 记事
host: bedford.github.com

custom:
    category:
        life: 活在当下
        photography: 色影人生
        problems: 问题记录
        codereading: 代码分析
    categories:
      - name:  life
        title: 活在当下

      - name:  photography
        title: 色影人生

      - name:  problems
        title: 问题记录

      - name:  codereading
        title: 代码分析

meta:
    author:
        name: bedford
        email: bedford2001@gmail.com
        disqus: bedford2001                         # Disqus缩略标识
#gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: bedford                             # GitHub账号
# gravatar: 1cd8c12591616d8c22aaa624f8c07834  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
# gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
